<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use SoftDeletes;
    protected $table = 'roles';
    protected $fillable = ['name'];

    public static function getData($request)
    {
        $url = '?';
        $roles = Role::withCount('userRole')->orderBy('id', 'ASC');

        if (in_trashed($request)) {
            $roles = self::onlyTrashed();
            $url = create_paginate_url($url, 'trashed=true');
        }

        $roles = $roles->paginate(10);
        $roles = $roles->withPath($url);
        return $roles;
    }

    public function userRole()
    {
        return $this->hasMany(User::class, 'role_id', 'id');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function ($role) {
            User::where(['role_id' => $role->id])->update(['role_id' => 0]);
            UserAccess::where(['role_id' => $role->id])->delete();
        });
    }

}
